# 线上配置文件
# 注意开源时这个文件不要提交、或者不要填真实配置
spring:
  profiles:
    active: dev
  application:
    name: qingzhou-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/qingzhou?serverTimezone=UTC
    url: jdbc:mysql://114.55.130.173:3306/qingzhou?serverTimezone=UTC
    username: root
    #    password: 123456
    password: Zk+87233515
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # redis 配置
  redis:
    port: 6379
    host: 114.55.130.173
    password: zk87233515
    database: 1
server:
  port: 8088
  servlet:
    context-path: /api
    session:
      cookie:
        domain: 114.55.130.173
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
